/**
 * Quick task 260630-hct -- coarse, self-hosted IP -> region (country + subdivision)
 * lookup for anonymous aggregate telemetry.
 *
 * PRIVACY INVARIANT (mirrors src/utils/telemetry-hash.js posture):
 *   - `ip` is accepted as a function argument
 *   - it is used ONLY to compute an integer key for a binary-search range lookup
 *   - it is NEVER assigned to a module-level or long-lived variable
 *   - it is NEVER logged, NEVER written to disk, NEVER passed onward
 *   - the temporary `ip` parameter is the only place plaintext exists, and it
 *     leaves scope as soon as deriveRegion() returns
 *
 * Only the *dataset* is third-party (DB-IP IP-to-City Lite, CC-BY-4.0); the
 * lookup logic here is ours -- a sorted-range binary search over uint32 IPv4
 * forms. No live third-party geo API is contacted (that would leak every user's
 * raw IP to a third party, which is worse than the existing hashed-IP posture).
 *
 * WORLDWIDE / 256 MB MEMORY MODEL:
 *   The production dataset is WORLDWIDE (all countries, IPv4-only) and can be a
 *   few hundred thousand to a few million ranges. To stay within the 256 MB Fly
 *   VM (binding limit is process RSS) the parsed table is a struct-of-arrays:
 *
 *     _table = {
 *       n,                       // number of ranges
 *       starts:  Uint32Array(n), // inclusive uint32 IPv4 range starts (sorted asc)
 *       ends:    Uint32Array(n), // inclusive uint32 IPv4 range ends
 *       labelId: Uint32Array(n), // index into `labels` (deduped/interned)
 *       labels:  Array<{country, subdivision}>,  // interned; index === labelId
 *     }
 *
 *   Retained cost is ~12 bytes/range (3 x Uint32) + a tiny interned-label set
 *   (a few thousand distinct {country,subdivision} pairs worldwide). The file is
 *   read in 1 MB CHUNKS (never a whole-file Buffer or string) and scanned
 *   BYTE-BY-BYTE: integers are parsed directly from ASCII digits; only the short
 *   country/subdivision byte-ranges are decoded to strings, then interned. A
 *   first pass counts newlines for an exact typed-array allocation; a second
 *   pass fills, rewinding the file position to each chunk's last complete line so
 *   no partial line straddles a chunk. Working set during load is ~1 MB + the
 *   final typed arrays -- so a ~70 MB / 2 M-range worldwide file loads with a
 *   ~25-30 MB footprint (NOT a ~100 MB whole-file spike). This deliberately
 *   avoids the original object-array loader's blow-up AND three whole-file
 *   string hazards: a multi-MB transient string, V8 silently widening it to
 *   UTF-16 the moment a non-Latin1 subdivision name (CJK/Cyrillic) appears, and
 *   V8's ~512 MiB string-length cap.
 *
 *   The dataset is emitted PRE-SORTED by scripts/refresh-dbip-dataset.mjs, so
 *   there is NO load-time sort; the binary search relies on that ordering (the
 *   committed fixture is likewise kept sorted ascending by start_ip_int).
 *
 * GRACEFUL DEGRADATION (HARD requirement): if the production dataset file is
 * absent, unreadable, empty, or pathologically large (Buffer/file size limits),
 * every call returns the literal string 'unknown' and this module NEVER throws.
 * The server boots and ingests with no dataset present. The real artifact is
 * generated by scripts/refresh-dbip-dataset.mjs and is NOT committed; only a tiny
 * fixture (data/dbip-city-lite.fixture.csv) ships for tests.
 *
 * Dataset path resolution: process.env.DBIP_DATASET_PATH || the default
 * production artifact path under showcase/server/data/.
 *
 * Coarse IPv4-only is acceptable for this task: IPv6 or unparseable input
 * returns 'unknown'.
 *
 * tests/server-ip-geo.test.js exercises hit / miss / absent-dataset / malformed;
 * tests/server-ip-geo-scale.test.js exercises a large synthetic dataset.
 */

'use strict';

const fs = require('fs');
const path = require('path');

// Default production artifact path. The refresh script writes here; .gitignore
// excludes it (but keeps *.fixture.csv). Overridable via DBIP_DATASET_PATH.
const DEFAULT_DATASET_PATH = path.join(__dirname, '..', '..', 'data', 'dbip-city-lite.csv');

// Lazily-populated parsed table. Three states:
//   undefined -> not yet loaded (load on first call)
//   null      -> load attempted and failed/absent/empty (graceful 'unknown')
//   object    -> struct-of-arrays { n, starts, ends, labelId, labels } (see header)
let _table;

/**
 * Convert a dotted-quad IPv4 string to its uint32 form, or null if it is not a
 * well-formed IPv4 address (covers IPv6, IPv4-mapped-IPv6, garbage, empty).
 *
 * @param {unknown} ip
 * @returns {number|null}
 */
function ipv4ToInt(ip) {
  if (typeof ip !== 'string') return null;
  const parts = ip.split('.');
  if (parts.length !== 4) return null;
  let acc = 0;
  for (let i = 0; i < 4; i++) {
    const octet = parts[i];
    // Reject empty, non-digit, or out-of-range octets. Disallow leading-zero
    // ambiguity beyond a single '0' to keep parsing strict.
    if (!/^\d{1,3}$/.test(octet)) return null;
    const n = Number(octet);
    if (n > 255) return null;
    if (octet.length > 1 && octet[0] === '0') return null;
    acc = acc * 256 + n;
  }
  // Coerce to unsigned 32-bit.
  return acc >>> 0;
}

/**
 * Parse ONE compact-CSV line, given as the byte-range buf[start, end), into the
 * mutable accumulator `acc` ({ starts, ends, labelId, labels, labelMap, w }).
 * Line shape: `start_ip_int,end_ip_int,country,subdivision`. Blank/'#'/malformed
 * lines are silently skipped. Integers are parsed straight from ASCII digits
 * (zero allocation); only the short country/subdivision byte-ranges are decoded
 * to strings, then interned. Byte constants: 10='\n' 13='\r' 44=',' 35='#'
 * 32=' ' 9='\t' 48..57='0'..'9'.
 *
 * @param {Buffer} buf
 * @param {number} start inclusive
 * @param {number} end exclusive (caller has already excluded the newline byte)
 * @param {{starts:Uint32Array,ends:Uint32Array,labelId:Uint32Array,labels:Array,labelMap:Map,w:number}} acc
 */
function _parseLineBytes(buf, start, end, acc) {
  if (end > start && buf[end - 1] === 13) end--; // strip a trailing '\r'

  let p = start;
  while (p < end && (buf[p] === 32 || buf[p] === 9)) p++; // skip leading ws
  if (p >= end || buf[p] === 35) return; // blank / comment

  // start_ip_int (ASCII digits).
  let startInt = 0; let sawStart = false;
  while (p < end && buf[p] >= 48 && buf[p] <= 57) { startInt = startInt * 10 + (buf[p] - 48); p++; sawStart = true; }
  if (!sawStart || p >= end || buf[p] !== 44) return;
  p++;

  // end_ip_int (ASCII digits).
  let endInt = 0; let sawEnd = false;
  while (p < end && buf[p] >= 48 && buf[p] <= 57) { endInt = endInt * 10 + (buf[p] - 48); p++; sawEnd = true; }
  if (!sawEnd || p >= end || buf[p] !== 44) return;
  p++;

  // country: bytes up to the next ','.
  const cStart = p;
  while (p < end && buf[p] !== 44) p++;
  if (p >= end) return; // missing 3rd comma
  const cEnd = p;
  p++;

  // subdivision: the remainder of the line (kept whole even if it contains
  // commas -- though the transform strips commas from labels).
  const sStart = p;
  const sEnd = end;

  if (endInt < startInt) return;
  if (cEnd <= cStart) return; // empty country

  // Decode ONLY the short label byte-ranges to strings, then intern.
  const country = buf.toString('utf8', cStart, cEnd).trim();
  if (country === '') return;
  const subdivision = buf.toString('utf8', sStart, sEnd).trim();

  const key = country + '\x1F' + subdivision;
  let id = acc.labelMap.get(key);
  if (id === undefined) {
    id = acc.labels.length;
    acc.labels.push({ country, subdivision });
    acc.labelMap.set(key, id);
  }

  acc.starts[acc.w] = startInt >>> 0;
  acc.ends[acc.w] = endInt >>> 0;
  acc.labelId[acc.w] = id;
  acc.w += 1;
}

// Next newline (byte 10) in buf within [from, limit), or -1. The read buffer is
// reused, so its tail beyond `limit` holds stale bytes -- bound the search.
function _indexOfNewline(buf, from, limit) {
  const nl = buf.indexOf(10, from);
  return (nl < 0 || nl >= limit) ? -1 : nl;
}

// Read chunk size for the two-pass file scan. 1 MiB keeps the load working set
// tiny regardless of dataset size; lines are < ~64 bytes so one chunk holds many.
const LOAD_CHUNK_BYTES = 1 << 20;

/**
 * Lazy, once-only dataset load. Resolves the path from DBIP_DATASET_PATH or the
 * default, then reads the file in 1 MiB CHUNKS (never a whole-file Buffer/string):
 *   - pass 1 counts newline bytes for an exact typed-array allocation;
 *   - pass 2 fills the arrays, rewinding the file position to each chunk's last
 *     complete line so no partial line straddles a chunk boundary.
 * On ANY failure (absent / unreadable / empty / parse-empty / oversized) caches
 * `null` so subsequent calls do not re-stat the filesystem and the module
 * degrades to 'unknown' without throwing.
 *
 * @returns {{n:number, starts:Uint32Array, ends:Uint32Array, labelId:Uint32Array, labels:Array}|null}
 */
function loadTable() {
  if (_table !== undefined) return _table;
  const datasetPath = process.env.DBIP_DATASET_PATH || DEFAULT_DATASET_PATH;
  let fd = null;
  try {
    fd = fs.openSync(datasetPath, 'r');
    const buf = Buffer.allocUnsafe(LOAD_CHUNK_BYTES);

    // Pass 1: count newline bytes -> safe upper bound on row count.
    // maxRows = newlines + 1 covers a final line with no trailing newline; it
    // also over-counts blank/comment lines, which subarray() trims off later.
    let newlineCount = 0;
    let total = 0;
    let pos = 0;
    for (;;) {
      const n = fs.readSync(fd, buf, 0, LOAD_CHUNK_BYTES, pos);
      if (n === 0) break;
      pos += n;
      total += n;
      for (let i = 0; i < n; i++) if (buf[i] === 10) newlineCount++;
    }
    if (total === 0) { _table = null; return _table; }

    const maxRows = newlineCount + 1;
    const acc = {
      starts: new Uint32Array(maxRows),
      ends: new Uint32Array(maxRows),
      labelId: new Uint32Array(maxRows),
      labels: [],
      labelMap: new Map(),
      w: 0,
    };

    // Pass 2: parse only COMPLETE lines per chunk; rewind to the byte after the
    // last newline so the trailing partial line is re-read at the head of the
    // next chunk (no cross-chunk carry buffer needed).
    pos = 0;
    for (;;) {
      const n = fs.readSync(fd, buf, 0, LOAD_CHUNK_BYTES, pos);
      if (n === 0) break;

      let lastNL = -1;
      for (let i = n - 1; i >= 0; i--) { if (buf[i] === 10) { lastNL = i; break; } }

      let limit;
      if (lastNL === -1) {
        // No newline in a full chunk => a single line longer than the chunk.
        // Our rows are tiny so this is unreachable; guard against an infinite
        // loop by consuming the chunk as one (likely-malformed) line.
        limit = n;
        pos += n;
      } else {
        limit = lastNL;        // parse complete lines in [0, lastNL)
        pos += lastNL + 1;     // next read resumes just past that newline
      }

      let i = 0;
      while (i < limit) {
        let nl = _indexOfNewline(buf, i, limit);
        if (nl === -1) nl = limit; // last complete line ends exactly at `limit`
        _parseLineBytes(buf, i, nl, acc);
        i = nl + 1;
      }
    }

    if (acc.w === 0) { _table = null; return _table; }
    _table = {
      n: acc.w,
      starts: acc.starts.subarray(0, acc.w),
      ends: acc.ends.subarray(0, acc.w),
      labelId: acc.labelId.subarray(0, acc.w),
      labels: acc.labels,
    };
  } catch {
    // Absent / unreadable / oversized -> graceful degradation. Nothing sensitive
    // logged. Any chunk buffer is GC'd.
    _table = null;
  } finally {
    if (fd !== null) { try { fs.closeSync(fd); } catch { /* ignore */ } }
  }
  return _table;
}

/**
 * Derive a coarse { country, subdivision } region from a plaintext IP, or the
 * literal string 'unknown' when the IP is non-IPv4, falls outside every range,
 * or no dataset is loaded. NEVER throws; NEVER retains or logs the IP.
 *
 * @param {string} ip plaintext request IP (e.g. req.ip with trust proxy=1)
 * @returns {{country:string, subdivision:string}|'unknown'}
 */
function deriveRegion(ip) {
  const key = ipv4ToInt(ip);
  if (key === null) return 'unknown';

  const t = loadTable();
  if (!t || t.n === 0) return 'unknown';

  const { starts, ends, labelId, labels } = t;

  // Binary search for the range whose [start, end] contains key.
  let lo = 0;
  let hi = t.n - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >>> 1;
    if (key < starts[mid]) {
      hi = mid - 1;
    } else if (key > ends[mid]) {
      lo = mid + 1;
    } else {
      // Return a FRESH object, not the interned record -- callers must not be
      // able to mutate the shared label, and regionLabel() only reads the two
      // fields, so this is behaviourally identical to the old object array.
      const lab = labels[labelId[mid]];
      return { country: lab.country, subdivision: lab.subdivision };
    }
  }
  return 'unknown';
}

/**
 * Test-only: drop the cached table so a test can re-point DBIP_DATASET_PATH and
 * force a fresh load. Not used in production code paths.
 */
function _resetForTest() {
  _table = undefined;
}

module.exports = { deriveRegion, ipv4ToInt, _resetForTest };
module.exports.DEFAULT_DATASET_PATH = DEFAULT_DATASET_PATH;
