/**
 * Quick task 260630-hct -- coarse, self-hosted IP -> region (country + subdivision)
 * lookup for anonymous aggregate telemetry.
 *
 * PRIVACY INVARIANT (mirrors src/utils/telemetry-hash.js posture):
 *   - `ip` is accepted as a function argument
 *   - it is used ONLY to compute an integer key for a binary-search range lookup
 *   - it is NEVER assigned to a module-level or long-lived variable
 *   - it is NEVER logged, NEVER written to disk, NEVER passed onward
 *   - the temporary `ip` parameter is the only place plaintext exists, and it
 *     leaves scope as soon as deriveRegion() returns
 *
 * Only the *dataset* is third-party (DB-IP IP-to-City Lite, CC-BY-4.0); the
 * lookup logic here is ours -- a sorted-range binary search over uint32 IPv4
 * forms and 64-bit IPv6 prefixes. No live third-party geo API is contacted
 * (that would leak every user's raw IP to a third party, which is worse than
 * the existing hashed-IP posture).
 *
 * WORLDWIDE / 256 MB MEMORY MODEL:
 *   The production dataset is WORLDWIDE (all countries, IPv4 + IPv6) and can be a
 *   few hundred thousand to a few million ranges. To stay within the 256 MB Fly
 *   VM (binding limit is process RSS) the parsed table is a struct-of-arrays:
 *
 *     _table = {
 *       n,                       // number of ranges
 *       starts:  Uint32Array(n), // inclusive uint32 IPv4 range starts (sorted asc)
 *       ends:    Uint32Array(n), // inclusive uint32 IPv4 range ends
 *       labelId: Uint32Array(n), // index into `labels` (deduped/interned)
 *       labels:  Array<{country, subdivision}>,  // interned; index === labelId
 *     }
 *
 *   Retained cost is ~12 bytes/range (3 x Uint32) + a tiny interned-label set
 *   (a few thousand distinct {country,subdivision} pairs worldwide). The file is
 *   read in 1 MB CHUNKS (never a whole-file Buffer or string) and scanned
 *   BYTE-BY-BYTE: integers are parsed directly from ASCII digits; only the short
 *   country/subdivision byte-ranges are decoded to strings, then interned. A
 *   first pass counts newlines for an exact typed-array allocation; a second
 *   pass fills, rewinding the file position to each chunk's last complete line so
 *   no partial line straddles a chunk. Working set during load is ~1 MB + the
 *   final typed arrays -- so a ~70 MB / 2 M-range worldwide file loads with a
 *   ~25-30 MB footprint (NOT a ~100 MB whole-file spike). This deliberately
 *   avoids the original object-array loader's blow-up AND three whole-file
 *   string hazards: a multi-MB transient string, V8 silently widening it to
 *   UTF-16 the moment a non-Latin1 subdivision name (CJK/Cyrillic) appears, and
 *   V8's ~512 MiB string-length cap.
 *
 *   The dataset is emitted PRE-SORTED by scripts/refresh-dbip-dataset.mjs, so
 *   there is NO load-time sort; the binary search relies on that ordering (the
 *   committed fixture is likewise kept sorted ascending by start_ip_int).
 *
 *   IPv6 uses a sibling table keyed on the top 64 bits of the address (the /64
 *   prefix; DB-IP carries no location below it). Each bound is two uint32 words,
 *   so the table is 5 x Uint32 = 20 bytes/range (~42 MB for the ~2.2 M-range
 *   worldwide file) and loads without BigInt. It is read the same chunked way
 *   from DBIP_IPV6_DATASET_PATH (or a sibling of the IPv4 path: `*.ipv6.csv` /
 *   `*.ipv6.fixture.csv`). Native IPv6 (Jio / 2405:201:: and similar) looks up
 *   here; CIDR `/56` keys do not parse and stay 'unknown'. IPv4-mapped IPv6
 *   (`::ffff:a.b.c.d`) still unwraps to IPv4.
 *
 *   DB-IP labels private/reserved space (10/8, 127/8, ::1, fe80::, Fly 6PN
 *   fdaa::) as country 'ZZ'; both tables report that as 'unknown', never as a
 *   region.
 *
 * GRACEFUL DEGRADATION (HARD requirement): if the production dataset file is
 * absent, unreadable, empty, or pathologically large (Buffer/file size limits),
 * every call returns the literal string 'unknown' and this module NEVER throws.
 * The server boots and ingests with no dataset present. The real artifact is
 * generated by scripts/refresh-dbip-dataset.mjs and is NOT committed; only tiny
 * fixtures (data/dbip-city-lite.fixture.csv and .ipv6.fixture.csv) ship for tests.
 *
 * Dataset path resolution: process.env.DBIP_DATASET_PATH || the default
 * production artifact path under showcase/server/data/. IPv6: DBIP_IPV6_DATASET_PATH
 * or a sibling of the IPv4 path.
 *
 * tests/server-ip-geo.test.js exercises hit / miss / absent-dataset / malformed;
 * tests/server-ip-geo-scale.test.js exercises a large synthetic dataset.
 */

'use strict';

const fs = require('fs');
const path = require('path');

// Default production artifact path. The refresh script writes here; .gitignore
// excludes it (but keeps *.fixture.csv). Overridable via DBIP_DATASET_PATH.
const DEFAULT_DATASET_PATH = path.join(__dirname, '..', '..', 'data', 'dbip-city-lite.csv');
const DEFAULT_IPV6_DATASET_PATH = path.join(__dirname, '..', '..', 'data', 'dbip-city-lite.ipv6.csv');

// Lazily-populated parsed tables. Three states each:
//   undefined -> not yet loaded (load on first call)
//   null      -> load attempted and failed/absent/empty (graceful 'unknown')
//   object    -> struct-of-arrays (see header)
let _table;
let _ipv6Table;

/** Sibling IPv6 artifact for an IPv4 compact-CSV path. */
function siblingIpv6Path(ipv4Path) {
  if (typeof ipv4Path !== 'string' || ipv4Path === '') return DEFAULT_IPV6_DATASET_PATH;
  if (ipv4Path.endsWith('.fixture.csv')) {
    return ipv4Path.replace(/\.fixture\.csv$/, '.ipv6.fixture.csv');
  }
  if (ipv4Path.endsWith('.csv')) return ipv4Path.slice(0, -4) + '.ipv6.csv';
  return ipv4Path + '.ipv6';
}

function resolveIpv6DatasetPath() {
  if (process.env.DBIP_IPV6_DATASET_PATH) return process.env.DBIP_IPV6_DATASET_PATH;
  return siblingIpv6Path(process.env.DBIP_DATASET_PATH || DEFAULT_DATASET_PATH);
}

/**
 * If `ip` is an IPv4-mapped IPv6 address, return the dotted-quad IPv4 form.
 * Node and Fly both emit `::ffff:a.b.c.d` (and occasionally `:ffff:a.b.c.d`)
 * for IPv4 clients on an IPv6 socket. Unmapped IPv4 and native IPv6 are
 * returned unchanged so the IPv4 parser / IPv6-unknown path can decide.
 *
 * @param {string} ip
 * @returns {string}
 */
function unwrapIpv4Mapped(ip) {
  const mapped = /(?:^|:)ffff:(\d{1,3}(?:\.\d{1,3}){3})$/i.exec(ip.trim());
  return mapped ? mapped[1] : ip;
}

/** Coarse IP family for diagnosing 'unknown' region. Never the address itself. */
const GEO_KIND = Object.freeze({
  IPV4: 'ipv4',
  IPV4_MAPPED: 'ipv4-mapped',
  IPV6: 'ipv6',
  IPV6_ULA: 'ipv6-ula',
  IPV6_CIDR: 'ipv6-cidr',
  EMPTY: 'empty',
  OTHER: 'other',
});

/**
 * Classify an address family without retaining it. Used to persist *why*
 * region is 'unknown' (Fly 6PN IPv6 vs native IPv6 vs unparseable) so we can
 * tell lookup-misses from "geo is IPv4-only".
 *
 * @param {unknown} ip
 * @returns {string} one of GEO_KIND values
 */
function classifyIp(ip) {
  if (typeof ip !== 'string') return GEO_KIND.EMPTY;
  const s = ip.trim();
  if (s === '') return GEO_KIND.EMPTY;
  const unwrapped = unwrapIpv4Mapped(s);
  const mapped = unwrapped !== s;
  if (ipv4ToInt(unwrapped) !== null) return mapped ? GEO_KIND.IPV4_MAPPED : GEO_KIND.IPV4;
  if (s.includes(':')) {
    if (s.includes('/')) return GEO_KIND.IPV6_CIDR;
    const head = s.toLowerCase();
    if (head.startsWith('fd') || head.startsWith('fc')) return GEO_KIND.IPV6_ULA;
    return GEO_KIND.IPV6;
  }
  return GEO_KIND.OTHER;
}

/**
 * Convert a dotted-quad IPv4 string (or IPv4-mapped IPv6) to its uint32 form,
 * or null if it is not a well-formed IPv4 address (native IPv6, garbage, empty).
 *
 * @param {unknown} ip
 * @returns {number|null}
 */
function ipv4ToInt(ip) {
  if (typeof ip !== 'string') return null;
  ip = unwrapIpv4Mapped(ip);
  const parts = ip.split('.');
  if (parts.length !== 4) return null;
  let acc = 0;
  for (let i = 0; i < 4; i++) {
    const octet = parts[i];
    // Reject empty, non-digit, or out-of-range octets. Disallow leading-zero
    // ambiguity beyond a single '0' to keep parsing strict.
    if (!/^\d{1,3}$/.test(octet)) return null;
    const n = Number(octet);
    if (n > 255) return null;
    if (octet.length > 1 && octet[0] === '0') return null;
    acc = acc * 256 + n;
  }
  // Coerce to unsigned 32-bit.
  return acc >>> 0;
}

/**
 * Parse a native IPv6 address into its /64 prefix as two big-endian uint32
 * words, or null. Rejects CIDR (`/56` rate-limit keys), zone IDs, dotted mixed
 * form, and anything that is not exactly 8 hextets after `::` expansion. The
 * low 64 bits are validated but dropped: the table carries no location below /64.
 *
 * @param {unknown} ip
 * @returns {{hi:number, lo:number}|null}
 */
function ipv6ToPrefix64(ip) {
  if (typeof ip !== 'string') return null;
  const s = ip.trim().toLowerCase();
  if (s === '' || s.includes('/') || s.includes('%') || s.includes('.')) return null;
  if (!s.includes(':')) return null;

  const sides = s.split('::');
  if (sides.length > 2) return null;

  const parseSide = (side) => {
    if (side === '') return [];
    const parts = side.split(':');
    const out = [];
    for (let i = 0; i < parts.length; i++) {
      const p = parts[i];
      if (!/^[0-9a-f]{1,4}$/.test(p)) return null;
      out.push(parseInt(p, 16));
    }
    return out;
  };

  let groups;
  if (sides.length === 1) {
    groups = parseSide(sides[0]);
    if (!groups || groups.length !== 8) return null;
  } else {
    const head = parseSide(sides[0]);
    const tail = parseSide(sides[1]);
    if (!head || !tail) return null;
    const missing = 8 - head.length - tail.length;
    if (missing < 1) return null;
    groups = head.concat(new Array(missing).fill(0), tail);
  }

  return {
    hi: ((groups[0] << 16) | groups[1]) >>> 0,
    lo: ((groups[2] << 16) | groups[3]) >>> 0,
  };
}

/** Compare two 64-bit values given as uint32 (hi, lo) word pairs. */
function cmp64(aHi, aLo, bHi, bLo) {
  if (aHi !== bHi) return aHi < bHi ? -1 : 1;
  if (aLo !== bLo) return aLo < bLo ? -1 : 1;
  return 0;
}

/**
 * Parse exactly 8 ASCII hex digits at buf[p..p+8) into a uint32, or -1.
 *
 * @param {Buffer} buf
 * @param {number} p
 * @param {number} end
 * @returns {number}
 */
function _parseHex32(buf, p, end) {
  if (p + 8 > end) return -1;
  let n = 0;
  for (let i = p; i < p + 8; i++) {
    const c = buf[i];
    let d;
    if (c >= 48 && c <= 57) d = c - 48;
    else if (c >= 97 && c <= 102) d = c - 87;
    else if (c >= 65 && c <= 70) d = c - 55;
    else return -1;
    n = n * 16 + d;
  }
  return n;
}

/**
 * Parse ONE compact-CSV line, given as the byte-range buf[start, end), into the
 * mutable accumulator `acc` ({ starts, ends, labelId, labels, labelMap, w }).
 * Line shape: `start_ip_int,end_ip_int,country,subdivision`. Blank/'#'/malformed
 * lines are silently skipped. Integers are parsed straight from ASCII digits
 * (zero allocation); only the short country/subdivision byte-ranges are decoded
 * to strings, then interned. Byte constants: 10='\n' 13='\r' 44=',' 35='#'
 * 32=' ' 9='\t' 48..57='0'..'9'.
 *
 * @param {Buffer} buf
 * @param {number} start inclusive
 * @param {number} end exclusive (caller has already excluded the newline byte)
 * @param {{starts:Uint32Array,ends:Uint32Array,labelId:Uint32Array,labels:Array,labelMap:Map,w:number}} acc
 */
function _parseLineBytes(buf, start, end, acc) {
  if (end > start && buf[end - 1] === 13) end--; // strip a trailing '\r'

  let p = start;
  while (p < end && (buf[p] === 32 || buf[p] === 9)) p++; // skip leading ws
  if (p >= end || buf[p] === 35) return; // blank / comment

  // start_ip_int (ASCII digits).
  let startInt = 0; let sawStart = false;
  while (p < end && buf[p] >= 48 && buf[p] <= 57) { startInt = startInt * 10 + (buf[p] - 48); p++; sawStart = true; }
  if (!sawStart || p >= end || buf[p] !== 44) return;
  p++;

  // end_ip_int (ASCII digits).
  let endInt = 0; let sawEnd = false;
  while (p < end && buf[p] >= 48 && buf[p] <= 57) { endInt = endInt * 10 + (buf[p] - 48); p++; sawEnd = true; }
  if (!sawEnd || p >= end || buf[p] !== 44) return;
  p++;

  // country: bytes up to the next ','.
  const cStart = p;
  while (p < end && buf[p] !== 44) p++;
  if (p >= end) return; // missing 3rd comma
  const cEnd = p;
  p++;

  // subdivision: the remainder of the line (kept whole even if it contains
  // commas -- though the transform strips commas from labels).
  const sStart = p;
  const sEnd = end;

  if (endInt < startInt) return;
  if (cEnd <= cStart) return; // empty country

  // Decode ONLY the short label byte-ranges to strings, then intern.
  const country = buf.toString('utf8', cStart, cEnd).trim();
  if (country === '') return;
  const subdivision = buf.toString('utf8', sStart, sEnd).trim();

  const key = country + '\x1F' + subdivision;
  let id = acc.labelMap.get(key);
  if (id === undefined) {
    id = acc.labels.length;
    acc.labels.push({ country, subdivision });
    acc.labelMap.set(key, id);
  }

  acc.starts[acc.w] = startInt >>> 0;
  acc.ends[acc.w] = endInt >>> 0;
  acc.labelId[acc.w] = id;
  acc.w += 1;
}

// Next newline (byte 10) in buf within [from, limit), or -1. The read buffer is
// reused, so its tail beyond `limit` holds stale bytes -- bound the search.
function _indexOfNewline(buf, from, limit) {
  const nl = buf.indexOf(10, from);
  return (nl < 0 || nl >= limit) ? -1 : nl;
}

// Read chunk size for the two-pass file scan. 1 MiB keeps the load working set
// tiny regardless of dataset size; lines are < ~64 bytes so one chunk holds many.
const LOAD_CHUNK_BYTES = 1 << 20;

/**
 * Lazy, once-only dataset load. Resolves the path from DBIP_DATASET_PATH or the
 * default, then reads the file in 1 MiB CHUNKS (never a whole-file Buffer/string):
 *   - pass 1 counts newline bytes for an exact typed-array allocation;
 *   - pass 2 fills the arrays, rewinding the file position to each chunk's last
 *     complete line so no partial line straddles a chunk boundary.
 * On ANY failure (absent / unreadable / empty / parse-empty / oversized) caches
 * `null` so subsequent calls do not re-stat the filesystem and the module
 * degrades to 'unknown' without throwing.
 *
 * @returns {{n:number, starts:Uint32Array, ends:Uint32Array, labelId:Uint32Array, labels:Array}|null}
 */
function loadTable() {
  if (_table !== undefined) return _table;
  const datasetPath = process.env.DBIP_DATASET_PATH || DEFAULT_DATASET_PATH;
  let fd = null;
  try {
    fd = fs.openSync(datasetPath, 'r');
    const buf = Buffer.allocUnsafe(LOAD_CHUNK_BYTES);

    // Pass 1: count newline bytes -> safe upper bound on row count.
    // maxRows = newlines + 1 covers a final line with no trailing newline; it
    // also over-counts blank/comment lines, which subarray() trims off later.
    let newlineCount = 0;
    let total = 0;
    let pos = 0;
    for (;;) {
      const n = fs.readSync(fd, buf, 0, LOAD_CHUNK_BYTES, pos);
      if (n === 0) break;
      pos += n;
      total += n;
      for (let i = 0; i < n; i++) if (buf[i] === 10) newlineCount++;
    }
    if (total === 0) { _table = null; return _table; }

    const maxRows = newlineCount + 1;
    const acc = {
      starts: new Uint32Array(maxRows),
      ends: new Uint32Array(maxRows),
      labelId: new Uint32Array(maxRows),
      labels: [],
      labelMap: new Map(),
      w: 0,
    };

    // Pass 2: parse only COMPLETE lines per chunk; rewind to the byte after the
    // last newline so the trailing partial line is re-read at the head of the
    // next chunk (no cross-chunk carry buffer needed).
    pos = 0;
    for (;;) {
      const n = fs.readSync(fd, buf, 0, LOAD_CHUNK_BYTES, pos);
      if (n === 0) break;

      let lastNL = -1;
      for (let i = n - 1; i >= 0; i--) { if (buf[i] === 10) { lastNL = i; break; } }

      let limit;
      if (lastNL === -1) {
        // No newline in a full chunk => a single line longer than the chunk.
        // Our rows are tiny so this is unreachable; guard against an infinite
        // loop by consuming the chunk as one (likely-malformed) line.
        limit = n;
        pos += n;
      } else {
        limit = lastNL;        // parse complete lines in [0, lastNL)
        pos += lastNL + 1;     // next read resumes just past that newline
      }

      let i = 0;
      while (i < limit) {
        let nl = _indexOfNewline(buf, i, limit);
        if (nl === -1) nl = limit; // last complete line ends exactly at `limit`
        _parseLineBytes(buf, i, nl, acc);
        i = nl + 1;
      }
    }

    if (acc.w === 0) { _table = null; return _table; }
    _table = {
      n: acc.w,
      starts: acc.starts.subarray(0, acc.w),
      ends: acc.ends.subarray(0, acc.w),
      labelId: acc.labelId.subarray(0, acc.w),
      labels: acc.labels,
    };
  } catch {
    // Absent / unreadable / oversized -> graceful degradation. Nothing sensitive
    // logged. Any chunk buffer is GC'd.
    _table = null;
  } finally {
    if (fd !== null) { try { fs.closeSync(fd); } catch { /* ignore */ } }
  }
  return _table;
}

/**
 * Parse ONE compact IPv6 CSV line: start64,end64,country,subdivision where each
 * bound is exactly 16 hex digits (the inclusive /64 prefix). Blank, '#', and
 * malformed lines -- including the old decimal-halves format -- are skipped.
 *
 * @param {Buffer} buf
 * @param {number} start
 * @param {number} end
 * @param {{startHi:Uint32Array,startLo:Uint32Array,endHi:Uint32Array,endLo:Uint32Array,labelId:Uint32Array,labels:Array,labelMap:Map,w:number}} acc
 */
function _parseIpv6LineBytes(buf, start, end, acc) {
  if (end > start && buf[end - 1] === 13) end--;

  let p = start;
  while (p < end && (buf[p] === 32 || buf[p] === 9)) p++;
  if (p >= end || buf[p] === 35) return;

  const startHi = _parseHex32(buf, p, end);
  const startLo = _parseHex32(buf, p + 8, end);
  if (startHi < 0 || startLo < 0 || p + 16 >= end || buf[p + 16] !== 44) return;
  p += 17;

  const endHi = _parseHex32(buf, p, end);
  const endLo = _parseHex32(buf, p + 8, end);
  if (endHi < 0 || endLo < 0 || p + 16 >= end || buf[p + 16] !== 44) return;
  p += 17;

  const cStart = p;
  while (p < end && buf[p] !== 44) p++;
  if (p >= end) return;
  const cEnd = p;
  p++;

  if (cmp64(endHi, endLo, startHi, startLo) < 0) return;
  if (cEnd <= cStart) return;

  const country = buf.toString('utf8', cStart, cEnd).trim();
  if (country === '') return;
  const subdivision = buf.toString('utf8', p, end).trim();

  const key = country + '\x1F' + subdivision;
  let id = acc.labelMap.get(key);
  if (id === undefined) {
    id = acc.labels.length;
    acc.labels.push({ country, subdivision });
    acc.labelMap.set(key, id);
  }

  acc.startHi[acc.w] = startHi;
  acc.startLo[acc.w] = startLo;
  acc.endHi[acc.w] = endHi;
  acc.endLo[acc.w] = endLo;
  acc.labelId[acc.w] = id;
  acc.w += 1;
}

/**
 * Lazy, once-only IPv6 dataset load. Same chunked two-pass scan as loadTable.
 * Path: DBIP_IPV6_DATASET_PATH or a sibling of the IPv4 compact CSV.
 *
 * @returns {{n:number, startHi:Uint32Array, startLo:Uint32Array, endHi:Uint32Array, endLo:Uint32Array, labelId:Uint32Array, labels:Array}|null}
 */
function loadIpv6Table() {
  if (_ipv6Table !== undefined) return _ipv6Table;
  const datasetPath = resolveIpv6DatasetPath();
  let fd = null;
  try {
    fd = fs.openSync(datasetPath, 'r');
    const buf = Buffer.allocUnsafe(LOAD_CHUNK_BYTES);

    let newlineCount = 0;
    let total = 0;
    let pos = 0;
    for (;;) {
      const n = fs.readSync(fd, buf, 0, LOAD_CHUNK_BYTES, pos);
      if (n === 0) break;
      pos += n;
      total += n;
      for (let i = 0; i < n; i++) if (buf[i] === 10) newlineCount++;
    }
    if (total === 0) { _ipv6Table = null; return _ipv6Table; }

    const maxRows = newlineCount + 1;
    const acc = {
      startHi: new Uint32Array(maxRows),
      startLo: new Uint32Array(maxRows),
      endHi: new Uint32Array(maxRows),
      endLo: new Uint32Array(maxRows),
      labelId: new Uint32Array(maxRows),
      labels: [],
      labelMap: new Map(),
      w: 0,
    };

    pos = 0;
    for (;;) {
      const n = fs.readSync(fd, buf, 0, LOAD_CHUNK_BYTES, pos);
      if (n === 0) break;

      let lastNL = -1;
      for (let i = n - 1; i >= 0; i--) { if (buf[i] === 10) { lastNL = i; break; } }

      let limit;
      if (lastNL === -1) {
        limit = n;
        pos += n;
      } else {
        limit = lastNL;
        pos += lastNL + 1;
      }

      let i = 0;
      while (i < limit) {
        let nl = _indexOfNewline(buf, i, limit);
        if (nl === -1) nl = limit;
        _parseIpv6LineBytes(buf, i, nl, acc);
        i = nl + 1;
      }
    }

    if (acc.w === 0) { _ipv6Table = null; return _ipv6Table; }
    _ipv6Table = {
      n: acc.w,
      startHi: acc.startHi.subarray(0, acc.w),
      startLo: acc.startLo.subarray(0, acc.w),
      endHi: acc.endHi.subarray(0, acc.w),
      endLo: acc.endLo.subarray(0, acc.w),
      labelId: acc.labelId.subarray(0, acc.w),
      labels: acc.labels,
    };
  } catch {
    _ipv6Table = null;
  } finally {
    if (fd !== null) { try { fs.closeSync(fd); } catch { /* ignore */ } }
  }
  return _ipv6Table;
}

// DB-IP marks private/reserved space (RFC 1918, loopback, link-local, ULA incl.
// Fly 6PN) as country 'ZZ'. That is not a place, so it must not become a region.
const RESERVED_COUNTRY = 'ZZ';

// Return a FRESH object so callers cannot mutate the interned label.
function regionFromLabel(lab) {
  if (lab.country === RESERVED_COUNTRY) return 'unknown';
  return { country: lab.country, subdivision: lab.subdivision };
}

function lookupIpv6(hi, lo) {
  const t = loadIpv6Table();
  if (!t || t.n === 0) return 'unknown';

  let left = 0;
  let right = t.n - 1;
  while (left <= right) {
    const mid = (left + right) >>> 1;
    if (cmp64(hi, lo, t.startHi[mid], t.startLo[mid]) < 0) {
      right = mid - 1;
    } else if (cmp64(hi, lo, t.endHi[mid], t.endLo[mid]) > 0) {
      left = mid + 1;
    } else {
      return regionFromLabel(t.labels[t.labelId[mid]]);
    }
  }
  return 'unknown';
}

/**
 * Derive a coarse { country, subdivision } region from a plaintext IP, or the
 * literal string 'unknown' when the IP falls outside every range, lands in
 * DB-IP's reserved 'ZZ' space, or no dataset is loaded. IPv4 (including mapped ::ffff:a.b.c.d) uses the IPv4 table; native
 * IPv6 uses the sibling IPv6 table. NEVER throws; NEVER retains or logs the IP.
 *
 * @param {string} ip plaintext request IP (Fly-Client-IP / req.ip)
 * @returns {{country:string, subdivision:string}|'unknown'}
 */
function deriveRegion(ip) {
  const key = ipv4ToInt(ip);
  if (key !== null) {
    const t = loadTable();
    if (!t || t.n === 0) return 'unknown';

    const { starts, ends, labelId, labels } = t;

    let lo = 0;
    let hi = t.n - 1;
    while (lo <= hi) {
      const mid = (lo + hi) >>> 1;
      if (key < starts[mid]) {
        hi = mid - 1;
      } else if (key > ends[mid]) {
        lo = mid + 1;
      } else {
        return regionFromLabel(labels[labelId[mid]]);
      }
    }
    return 'unknown';
  }

  const prefix = ipv6ToPrefix64(ip);
  if (!prefix) return 'unknown';
  return lookupIpv6(prefix.hi, prefix.lo);
}

/**
 * Test-only: drop the cached tables so a test can re-point dataset paths and
 * force a fresh load. Not used in production code paths.
 */
function _resetForTest() {
  _table = undefined;
  _ipv6Table = undefined;
}

module.exports = {
  deriveRegion,
  ipv4ToInt,
  ipv6ToPrefix64,
  unwrapIpv4Mapped,
  classifyIp,
  GEO_KIND,
  siblingIpv6Path,
  _resetForTest,
};
module.exports.DEFAULT_DATASET_PATH = DEFAULT_DATASET_PATH;
module.exports.DEFAULT_IPV6_DATASET_PATH = DEFAULT_IPV6_DATASET_PATH;
