/**
 * Quick task 260630-hct -- coarse, self-hosted IP -> region (country + subdivision)
 * lookup for anonymous aggregate telemetry.
 *
 * PRIVACY INVARIANT (mirrors src/utils/telemetry-hash.js posture):
 *   - `ip` is accepted as a function argument
 *   - it is used ONLY to compute an integer key for a binary-search range lookup
 *   - it is NEVER assigned to a module-level or long-lived variable
 *   - it is NEVER logged, NEVER written to disk, NEVER passed onward
 *   - the temporary `ip` parameter is the only place plaintext exists, and it
 *     leaves scope as soon as deriveRegion() returns
 *
 * Only the *dataset* is third-party (DB-IP IP-to-City Lite, CC-BY-4.0); the
 * lookup logic here is ours -- a sorted-range binary search over uint32 IPv4
 * forms. No live third-party geo API is contacted (that would leak every user's
 * raw IP to a third party, which is worse than the existing hashed-IP posture).
 *
 * GRACEFUL DEGRADATION (HARD requirement): if the production dataset file is
 * absent, unreadable, or empty, every call returns the literal string
 * 'unknown' and this module NEVER throws. The server boots and ingests with no
 * dataset present. The real ~100MB artifact is generated by
 * scripts/refresh-dbip-dataset.mjs and is NOT committed; only a tiny fixture
 * (data/dbip-city-lite.fixture.csv) ships for tests.
 *
 * Dataset path resolution: process.env.DBIP_DATASET_PATH || the default
 * production artifact path under showcase/server/data/.
 *
 * Coarse IPv4-only is acceptable for this task: IPv6 or unparseable input
 * returns 'unknown'.
 *
 * tests/server-ip-geo.test.js exercises hit / miss / absent-dataset / malformed.
 */

'use strict';

const fs = require('fs');
const path = require('path');

// Default production artifact path. The refresh script writes here; .gitignore
// excludes it (but keeps *.fixture.csv). Overridable via DBIP_DATASET_PATH.
const DEFAULT_DATASET_PATH = path.join(__dirname, '..', '..', 'data', 'dbip-city-lite.csv');

// Lazily-populated parsed table. Three states:
//   undefined -> not yet loaded (load on first call)
//   null      -> load attempted and failed/absent/empty (graceful 'unknown')
//   Array     -> sorted ranges [{ startIpInt, endIpInt, country, subdivision }, ...]
let _table; // eslint-disable-line no-unused-vars -- module-private cache

/**
 * Convert a dotted-quad IPv4 string to its uint32 form, or null if it is not a
 * well-formed IPv4 address (covers IPv6, IPv4-mapped-IPv6, garbage, empty).
 *
 * @param {unknown} ip
 * @returns {number|null}
 */
function ipv4ToInt(ip) {
  if (typeof ip !== 'string') return null;
  const parts = ip.split('.');
  if (parts.length !== 4) return null;
  let acc = 0;
  for (let i = 0; i < 4; i++) {
    const octet = parts[i];
    // Reject empty, non-digit, or out-of-range octets. Disallow leading-zero
    // ambiguity beyond a single '0' to keep parsing strict.
    if (!/^\d{1,3}$/.test(octet)) return null;
    const n = Number(octet);
    if (n > 255) return null;
    if (octet.length > 1 && octet[0] === '0') return null;
    acc = acc * 256 + n;
  }
  // Coerce to unsigned 32-bit.
  return acc >>> 0;
}

/**
 * Parse the compact range CSV into a sorted array of range records.
 * Lines: `start_ip_int,end_ip_int,country,subdivision`. '#'/blank lines skipped.
 * Returns null if the text yields zero usable rows.
 *
 * @param {string} text
 * @returns {Array<{startIpInt:number,endIpInt:number,country:string,subdivision:string}>|null}
 */
function parseDataset(text) {
  const out = [];
  const lines = text.split(/\r?\n/);
  for (const raw of lines) {
    const line = raw.trim();
    if (line === '' || line.startsWith('#')) continue;
    // Split into at most 4 fields; subdivision may legitimately contain commas
    // in upstream data, so keep everything after the 3rd comma as subdivision.
    const firstComma = line.indexOf(',');
    const secondComma = line.indexOf(',', firstComma + 1);
    const thirdComma = line.indexOf(',', secondComma + 1);
    if (firstComma < 0 || secondComma < 0 || thirdComma < 0) continue;
    const startIpInt = Number(line.slice(0, firstComma));
    const endIpInt = Number(line.slice(firstComma + 1, secondComma));
    const country = line.slice(secondComma + 1, thirdComma).trim();
    const subdivision = line.slice(thirdComma + 1).trim();
    if (!Number.isFinite(startIpInt) || !Number.isFinite(endIpInt)) continue;
    if (endIpInt < startIpInt) continue;
    if (country === '') continue;
    out.push({
      startIpInt: startIpInt >>> 0,
      endIpInt: endIpInt >>> 0,
      country,
      subdivision,
    });
  }
  if (out.length === 0) return null;
  // Sort ascending by range start so we can binary-search.
  out.sort((a, b) => a.startIpInt - b.startIpInt);
  return out;
}

/**
 * Lazy, once-only dataset load. Resolves the path from DBIP_DATASET_PATH or the
 * default. On ANY failure (absent / unreadable / empty / parse-empty) caches
 * `null` so subsequent calls do not re-stat the filesystem and the module
 * degrades to 'unknown' without throwing.
 *
 * @returns {Array|null}
 */
function loadTable() {
  if (_table !== undefined) return _table;
  const datasetPath = process.env.DBIP_DATASET_PATH || DEFAULT_DATASET_PATH;
  try {
    const text = fs.readFileSync(datasetPath, 'utf8');
    _table = parseDataset(text); // may be null if no usable rows
  } catch {
    // Absent or unreadable -> graceful degradation. Nothing sensitive logged.
    _table = null;
  }
  return _table;
}

/**
 * Derive a coarse { country, subdivision } region from a plaintext IP, or the
 * literal string 'unknown' when the IP is non-IPv4, falls outside every range,
 * or no dataset is loaded. NEVER throws; NEVER retains or logs the IP.
 *
 * @param {string} ip plaintext request IP (e.g. req.ip with trust proxy=1)
 * @returns {{country:string, subdivision:string}|'unknown'}
 */
function deriveRegion(ip) {
  const key = ipv4ToInt(ip);
  if (key === null) return 'unknown';

  const table = loadTable();
  if (!table || table.length === 0) return 'unknown';

  // Binary search for the range whose [startIpInt, endIpInt] contains key.
  let lo = 0;
  let hi = table.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >>> 1;
    const r = table[mid];
    if (key < r.startIpInt) {
      hi = mid - 1;
    } else if (key > r.endIpInt) {
      lo = mid + 1;
    } else {
      return { country: r.country, subdivision: r.subdivision };
    }
  }
  return 'unknown';
}

/**
 * Test-only: drop the cached table so a test can re-point DBIP_DATASET_PATH and
 * force a fresh load. Not used in production code paths.
 */
function _resetForTest() {
  _table = undefined;
}

module.exports = { deriveRegion, ipv4ToInt, _resetForTest };
module.exports.DEFAULT_DATASET_PATH = DEFAULT_DATASET_PATH;
