/**
 * Quick task 260630-hct (worldwide) -- ip-geo.js scale / memory-safety check.
 *
 * The worldwide DB-IP dataset is hundreds of thousands to a few million ranges.
 * This test builds a large synthetic compact dataset (default 1,000,000 ranges),
 * points DBIP_DATASET_PATH at it, and verifies the struct-of-arrays loader
 * (a) parses it without OOM/throw, (b) answers binary-search lookups correctly at
 * scale, incl. a multibyte subdivision, and (c) returns 'unknown' for gap /
 * out-of-range IPs.
 *
 * Memory: the dataset file is generated by STREAMING (no large in-process array),
 * and the loader's footprint is measured in an ISOLATED child process that does
 * nothing but load + look up -- so the reported RSS reflects the real server
 * scenario, not this test's generation overhead. RSS is printed for observability
 * and softly asserted under a generous ceiling well below the 256 MB VM limit.
 *
 * No framework; PASS/FAIL counter + non-zero exit on failure.
 * Run: node tests/server-ip-geo-scale.test.js
 */

'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

const IP_GEO = path.join(__dirname, '..', 'showcase', 'server', 'src', 'utils', 'ip-geo');
const ipGeo = require(IP_GEO);

let passed = 0;
let failed = 0;
function check(label, cond, detail) {
  if (cond) { passed += 1; console.log(`  PASS: ${label}`); }
  else { failed += 1; console.log(`  FAIL: ${label} -- ${detail}`); }
}

function intToIp(n) {
  return [(n >>> 24) & 255, (n >>> 16) & 255, (n >>> 8) & 255, n & 255].join('.');
}

// Distinct labels cycled across the synthetic ranges; index 5 is multibyte.
const LABELS = [
  ['US', 'California'], ['US', 'Texas'], ['GB', 'England'], ['DE', 'Bavaria'],
  ['IN', 'Maharashtra'], ['BR', 'São Paulo'], ['JP', 'Tokyo'],
];
const N = 1000000;    // number of synthetic ranges (~realistic worldwide upper end)
const STRIDE = 512;   // 256-wide range followed by a 256-wide gap (exercises misses)
const tmpPath = path.join(os.tmpdir(), `fsb-ipgeo-scale-${process.pid}.csv`);

console.log('--- server-ip-geo-scale (260630-hct) ---');

try {
  // Build a large, sorted, valid compact dataset by STREAMING in <=1 MB chunks --
  // never retain a millions-long array (that would pollute this process's RSS and
  // defeat the point of the measurement). Max start = N*STRIDE < 2^32.
  const fd = fs.openSync(tmpPath, 'w');
  fs.writeSync(fd, '# synthetic scale fixture (server-ip-geo-scale)\n');
  let buf = '';
  for (let i = 0; i < N; i++) {
    const start = i * STRIDE;
    const lab = LABELS[i % LABELS.length];
    buf += `${start},${start + 255},${lab[0]},${lab[1]}\n`;
    if (buf.length >= (1 << 20)) { fs.writeSync(fd, buf); buf = ''; }
  }
  if (buf) fs.writeSync(fd, buf);
  fs.closeSync(fd);

  process.env.DBIP_DATASET_PATH = tmpPath;
  ipGeo._resetForTest();

  function expectHit(i, offset) {
    const start = i * STRIDE;
    const lab = LABELS[i % LABELS.length];
    const ip = intToIp(start + offset);
    const r = ipGeo.deriveRegion(ip);
    check(`range ${i} (${ip}) -> ${lab[0]}/${lab[1]}`,
      r && typeof r === 'object' && r.country === lab[0] && r.subdivision === lab[1],
      `got ${JSON.stringify(r)}`);
  }

  expectHit(0, 0);            // first range, start boundary (inclusive)
  expectHit(0, 255);          // first range, end boundary (inclusive)
  expectHit(123456, 100);     // deep-middle range
  expectHit(N - 1, 200);      // last range
  expectHit(5, 10);           // label index 5 -> BR/São Paulo (multibyte at scale)

  // Address inside a gap of a covered block -> 'unknown'.
  const gapIp = intToIp(100 * STRIDE + 300); // 300 is past the 256-wide range, before next start
  check(`gap address ${gapIp} -> unknown`, ipGeo.deriveRegion(gapIp) === 'unknown',
    `got ${JSON.stringify(ipGeo.deriveRegion(gapIp))}`);

  // Address above every range -> 'unknown'.
  const aboveIp = intToIp(N * STRIDE + 1000);
  check(`above-all address ${aboveIp} -> unknown`, ipGeo.deriveRegion(aboveIp) === 'unknown',
    `got ${JSON.stringify(ipGeo.deriveRegion(aboveIp))}`);

  // Isolated memory probe: a fresh process that ONLY loads the dataset + does one
  // lookup, then prints its peak RSS. This excludes this test's generation cost,
  // so the number reflects the actual server load path.
  const probe = `
    process.env.DBIP_DATASET_PATH = ${JSON.stringify(tmpPath)};
    const g = require(${JSON.stringify(IP_GEO)});
    const r = g.deriveRegion('8.8.8.8'); // triggers the lazy load
    if (typeof r === 'undefined') process.exit(3);
    console.log(JSON.stringify({ rss: process.memoryUsage().rss }));
  `;
  let probeRssMb = null;
  try {
    const out = execFileSync(process.execPath, ['-e', probe], { encoding: 'utf8' });
    probeRssMb = JSON.parse(out.trim()).rss / 1048576;
  } catch (e) {
    probeRssMb = null;
  }
  if (probeRssMb !== null) {
    console.log(`  [info] isolated loader RSS for ${N} ranges: ${probeRssMb.toFixed(1)}MB`);
    // Generous ceiling: a clean load of ~1M ranges should sit well under this and
    // far below the 256 MB VM. Soft guard against a future representation regression.
    check(`isolated loader RSS < 200MB (got ${probeRssMb.toFixed(1)}MB)`, probeRssMb < 200,
      `RSS ${probeRssMb.toFixed(1)}MB exceeds 200MB ceiling`);
  } else {
    console.log('  [info] isolated RSS probe unavailable (skipped, non-fatal)');
  }
} finally {
  try { fs.unlinkSync(tmpPath); } catch { /* best effort */ }
}

console.log(`\n=== server-ip-geo-scale results: ${passed} passed, ${failed} failed ===`);
if (failed > 0) process.exit(1);
process.exit(0);
