// content/selectors.js -- FSB Selector Generation and Resolution
// Contains the canonical generateSelector plus all selector utilities.
// Depends on: content/init.js (FSB namespace), content/utils.js (getClassName, stripUnicodeControl,
//   findElementByNormalizedAriaLabel), content/dom-state.js (elementCache, refMap, getElementIndexes)

(function() {
  if (window.__FSB_SKIP_INIT__) return;

  const FSB = window.FSB;
  const logger = FSB.logger;

  // ============================================================================
  // SELECTOR VALIDATION UTILITIES
  // ============================================================================

  /**
   * Validates whether a CSS selector uniquely identifies exactly one element
   * @param {string} selector - The CSS selector to validate
   * @param {Element|Document} root - The root element to search within (default: document)
   * @returns {Object} Validation result with isValid, isUnique, count, selector, and optional error
   */
  function validateSelectorUniqueness(selector, root = document) {
    try {
      const matches = root.querySelectorAll(selector);
      const count = matches.length;
      return {
        isValid: true,
        isUnique: count === 1,
        count: count,
        selector: selector
      };
    } catch (error) {
      return {
        isValid: false,
        isUnique: false,
        count: 0,
        selector: selector,
        error: error.message
      };
    }
  }

  /**
   * Validates whether an XPath selector uniquely identifies exactly one element
   * @param {string} xpath - The XPath expression to validate
   * @param {Element|Document} root - The root element to search within (default: document)
   * @returns {Object} Validation result with isValid, isUnique, count, selector, and optional error
   */
  function validateXPathUniqueness(xpath, root = document) {
    try {
      const result = document.evaluate(
        xpath,
        root,
        null,
        XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,
        null
      );
      const count = result.snapshotLength;
      return {
        isValid: true,
        isUnique: count === 1,
        count: count,
        selector: xpath
      };
    } catch (error) {
      return {
        isValid: false,
        isUnique: false,
        count: 0,
        selector: xpath,
        error: error.message
      };
    }
  }

  // ============================================================================
  // ENHANCED ID AND CLASS FILTERING PATTERNS
  // ============================================================================

  /**
   * Pattern to match auto-generated IDs from common frameworks
   * Matches: UUID patterns, react-*, vue-*, ember-*, angular (ng-), radix-*, headless, etc.
   * @type {RegExp}
   */
  const AUTO_GENERATED_ID_PATTERN = /^[0-9a-f]{8}-|^uid-|^react-|^ember-|^:r[a-z0-9]+:|^__react|^ng-|^vue-|^el-|^radix-|^headless|^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

  /**
   * Checks if an ID appears to be auto-generated by a framework
   * @param {string} id - The ID to check
   * @returns {boolean} True if the ID appears to be auto-generated
   */
  function isAutoGeneratedId(id) {
    if (!id) {
      return false;
    }

    // Check against known framework patterns
    if (AUTO_GENERATED_ID_PATTERN.test(id)) {
      return true;
    }

    // Check for pure hex strings of 6+ characters (likely hashes)
    if (/^[0-9a-f]{6,}$/i.test(id)) {
      return true;
    }

    return false;
  }

  /**
   * Patterns to match dynamic/state classes that should be filtered out
   * These classes change based on UI state and are not stable for targeting
   * @type {RegExp[]}
   */
  const DYNAMIC_CLASS_PATTERNS = [
    /^(active|selected|hover|focus|disabled|loading|hidden|show|visible|open|closed)$/i,  // State classes
    /^(is-|has-|js-|css-)/i,  // State prefixes
    /^[a-z]{1,2}[0-9a-f]{4,}$/i,  // CSS Modules hashes (e.g., "a1b2c3d4")
    /^_[a-zA-Z0-9]+_[a-zA-Z0-9]+$/,  // Styled-components (e.g., "_Button_1a2b3")
    /^[A-Z][a-zA-Z]+__[a-zA-Z]+--/,  // BEM modifier states (e.g., "Block__element--modifier")
  ];

  /**
   * Filters out dynamic/state classes from a class string
   * Returns only stable classes suitable for selector generation
   * @param {string} classString - Space-separated class string
   * @returns {string[]} Array of stable class names
   */
  function filterDynamicClasses(classString) {
    if (!classString || typeof classString !== 'string') {
      return [];
    }

    const classes = classString.trim().split(/\s+/);

    return classes.filter(className => {
      // Skip empty strings
      if (!className) {
        return false;
      }

      // Check against all dynamic patterns
      for (const pattern of DYNAMIC_CLASS_PATTERNS) {
        if (pattern.test(className)) {
          return false;
        }
      }

      return true;
    });
  }

  // ============================================================================
  // BASIC SELECTOR GENERATION
  // ============================================================================

  // Generate basic selector for parent elements
  function generateBasicSelector(element) {
    if (element.id) return `#${element.id}`;
    if (element.className && typeof element.className === 'string') {
      const classes = element.className.trim().split(/\s+/).filter(c => c);
      if (classes.length > 0) return `.${classes[0]}`;
    }
    return element.tagName.toLowerCase();
  }

  // ============================================================================
  // CANONICAL generateSelector -- accessibility-first, comprehensive version
  // ============================================================================

  /**
   * Generate a reliable selector for an element
   * @param {Element} element - The element to generate a selector for
   * @returns {string|null} A CSS selector for the element
   */
  function generateSelector(element) {
    // EASY WIN #1: Accessibility-first selector generation (40% more stable)

    // Strategy 1: Prefer ID if available
    if (element.id) {
      return `#${element.id}`;
    }

    // Strategy 2: ARIA role-based selectors (most stable - Testing Library pattern)
    const role = element.getAttribute('role') || element.getAttribute('aria-role');
    const tag = element.tagName.toLowerCase();

    if (role) {
      // Try role + accessible name combination
      const ariaLabel = element.getAttribute('aria-label');
      const ariaLabelledBy = element.getAttribute('aria-labelledby');

      if (ariaLabel) {
        const roleWithLabel = `[role="${role}"][aria-label="${ariaLabel}"]`;
        if (document.querySelectorAll(roleWithLabel).length === 1) {
          return roleWithLabel;
        }
      }

      // Try role + tag combination
      const roleWithTag = `${tag}[role="${role}"]`;
      const roleMatches = document.querySelectorAll(roleWithTag);
      if (roleMatches.length === 1) {
        return roleWithTag;
      }
      if (roleMatches.length > 1) {
        const unique = makeUnique(roleWithTag, element);
        if (unique) return unique;
      }
    }

    // Strategy 3: Use unique attributes (accessibility-first order)
    const uniqueAttrs = [
      'aria-label',       // Accessibility first
      'aria-labelledby',
      'data-testid',      // Test IDs
      'data-test',
      'data-qa',
      'data-cy',
      'data-id'
    ];
    for (const attr of uniqueAttrs) {
      const value = element.getAttribute(attr);
      if (value) {
        const selector = `[${attr}="${value}"]`;
        // Verify uniqueness
        if (document.querySelectorAll(selector).length === 1) {
          return selector;
        }

        // Try with tag for better specificity
        const tagSelector = `${tag}${selector}`;
        if (document.querySelectorAll(tagSelector).length === 1) {
          return tagSelector;
        }
      }
    }

    // Strategy 3: Use classes with fallback strategies
    if (element.className && typeof element.className === 'string') {
      const classes = element.className.trim().split(/\s+/).filter(c => c);

      if (classes.length > 0) {
        // Escape CSS special characters in class names (e.g. CSS module hashes with +, ~, etc.)
        const escapeCSS = (cls) => cls.replace(/([!"#$%&'()*+,.\/:;<=>?@[\\\]^`{|}~])/g, '\\$1');
        const escapedClasses = classes.map(escapeCSS);

        // Try full class combination
        const fullSelector = `.${escapedClasses.join('.')}`;
        const fullMatches = document.querySelectorAll(fullSelector);
        if (fullMatches.length === 1) {
          return fullSelector;
        }
        if (fullMatches.length > 1 && fullMatches.length <= 3) {
          const unique = makeUnique(fullSelector, element);
          if (unique) return unique;
        }

        // IMPROVED: Try partial class combinations (more robust)
        // Try first 2 classes
        if (escapedClasses.length >= 2) {
          const partialSelector = `.${escapedClasses.slice(0, 2).join('.')}`;
          const partialMatches = document.querySelectorAll(partialSelector);
          if (partialMatches.length === 1) {
            return partialSelector;
          }
          if (partialMatches.length > 1 && partialMatches.length <= 5) {
            const unique = makeUnique(partialSelector, element);
            if (unique) return unique;
          }
        }

        // Try just the first class
        const singleClass = `.${escapedClasses[0]}`;
        const singleMatches = document.querySelectorAll(singleClass);
        if (singleMatches.length === 1) {
          return singleClass;
        }
        if (singleMatches.length > 1 && singleMatches.length <= 10) {
          const unique = makeUnique(singleClass, element);
          if (unique) return unique;
        }
      }
    }

    // Strategy 4: Tag + type combination
    if (element.type) {
      const typeSelector = `${tag}[type="${element.type}"]`;
      const typeMatches = document.querySelectorAll(typeSelector).length;
      if (typeMatches === 1) {
        return typeSelector;
      }
      if (typeMatches > 1 && typeMatches <= 5) {
        const unique = makeUnique(typeSelector, element);
        if (unique) return unique;
      }
    }

    // Strategy 5: Tag + name combination
    if (element.name) {
      const nameSelector = `${tag}[name="${element.name}"]`;
      const nameMatches = document.querySelectorAll(nameSelector).length;
      if (nameMatches === 1) {
        return nameSelector;
      }
      if (nameMatches > 1 && nameMatches <= 3) {
        const unique = makeUnique(nameSelector, element);
        if (unique) return unique;
      }
    }

    // Strategy 6: Tag + aria-label (even if not unique)
    const labelForTag = element.getAttribute('aria-label');
    if (labelForTag) {
      return `${tag}[aria-label="${labelForTag}"]`;
    }

    // Strategy 7: Tag + role combination
    const elemRole = element.getAttribute('role');
    if (elemRole) {
      const roleSelector = `${tag}[role="${elemRole}"]`;
      const roleCount = document.querySelectorAll(roleSelector).length;
      if (roleCount === 1) {
        return roleSelector;
      }
      if (roleCount > 1 && roleCount <= 5) {
        const unique = makeUnique(roleSelector, element);
        if (unique) return unique;
      }
    }

    // Fallback: Just the tag
    return tag;
  }

  // ============================================================================
  // ALTERNATIVE SELECTORS AND CLICKABILITY
  // ============================================================================

  /**
   * Check if an element appears to be clickable
   * @param {Element} element - The element to check
   * @returns {boolean} Whether the element seems clickable
   */
  function isClickable(element) {
    const clickableTags = ['A', 'BUTTON', 'INPUT'];
    if (clickableTags.includes(element.tagName)) return true;

    const style = window.getComputedStyle(element);
    if (style.cursor === 'pointer') return true;

    if (element.onclick || element.getAttribute('onclick')) return true;
    if (element.getAttribute('role') === 'button') return true;

    return false;
  }

  /**
   * Find alternative selectors for an element that couldn't be found.
   * PERF: Uses cached DOM queries to avoid multiple overlapping querySelectorAll calls.
   * @param {string} failedSelector - The selector that failed
   * @param {string} actionType - The type of action being attempted
   * @returns {Array} Array of alternative selectors to try
   */
  function findAlternativeSelectors(failedSelector, actionType) {
    const alternatives = [];

    // Extract meaningful parts from the failed selector
    const selectorParts = failedSelector.match(/[\w-]+/g) || [];
    const lowerParts = selectorParts.map(p => p.toLowerCase());

    // Helper: check if element text/attributes match any selector part
    function matchesParts(el) {
      const text = el.textContent?.trim().toLowerCase() || '';
      const ariaLabel = el.getAttribute('aria-label')?.toLowerCase() || '';
      const className = FSB.getClassName(el);
      const id = el.id || '';
      return lowerParts.some(part =>
        text.includes(part) ||
        ariaLabel.includes(part) ||
        className.includes(part) ||
        id.includes(part)
      );
    }

    if (actionType === 'click') {
      // PERF: Use cached element indexes instead of re-querying DOM
      const clickables = FSB.getElementIndexes().clickable;
      for (const el of clickables) {
        if (matchesParts(el)) {
          const selector = generateSelector(el);
          if (selector && !alternatives.includes(selector)) {
            alternatives.push(selector);
          }
        }
      }

      // Partial class match - only if not already found enough
      if (alternatives.length < 3 && failedSelector.includes('.')) {
        const className = failedSelector.match(/\.([^.\s]+)/)?.[1];
        if (className) {
          const classMatches = document.querySelectorAll(`[class*="${className}"]`);
          for (const el of classMatches) {
            if (el.tagName.match(/^(A|BUTTON|INPUT|SPAN|DIV)$/) && isClickable(el)) {
              const selector = generateSelector(el);
              if (selector && !alternatives.includes(selector)) {
                alternatives.push(selector);
              }
            }
          }
        }
      }
    }

    if (actionType === 'type') {
      // PERF: Use cached element indexes instead of re-querying DOM
      const inputs = FSB.getElementIndexes().input;
      for (const el of inputs) {
        const placeholder = el.placeholder?.toLowerCase() || '';
        const name = el.name?.toLowerCase() || '';
        const matches = lowerParts.some(part =>
          placeholder.includes(part) ||
          (el.getAttribute('aria-label') || '').toLowerCase().includes(part) ||
          name.includes(part) ||
          FSB.getClassName(el).includes(part) ||
          (el.id || '').includes(part)
        );
        if (matches) {
          const selector = generateSelector(el);
          if (selector && !alternatives.includes(selector)) {
            alternatives.push(selector);
          }
        }
      }
    }

    return alternatives;
  }

  // ============================================================================
  // SELECTOR SANITIZATION
  // ============================================================================

  /**
   * Sanitizes a CSS selector by removing invalid pseudo-selectors
   * that are not supported by native querySelector (e.g., jQuery's :contains())
   * @param {string} selector - The selector to sanitize
   * @returns {string} A valid CSS selector
   */
  function sanitizeSelector(selector) {
    return typeof selector === 'string' ? selector.trim() || null : null;
  }

  // ============================================================================
  // SHADOW DOM QUERY SUPPORT
  // ============================================================================

  // Query selector that supports shadow DOM
  // SPEED-04: Uses elementCache for faster repeated lookups
  function querySelectorWithShadow(selector) {
    // Never strip selector conditions: unsupported syntax must fail closed.
    const sanitized = sanitizeSelector(selector);
    if (!sanitized) {
      logger.warn('Cannot query with invalid selector', { sessionId: FSB.sessionId, selector });
      return null;
    }

    // SPEED-04: Check cache first for fast repeated lookups
    const cached = FSB.elementCache.get(sanitized);
    if (cached) {
      return cached;
    }

    let element = null;

    // Handle XPath selectors (start with // or /)
    if (sanitized.startsWith('//') || (sanitized.startsWith('/') && !sanitized.startsWith('/*'))) {
      try {
        const result = document.evaluate(
          sanitized, document, null,
          XPathResult.FIRST_ORDERED_NODE_TYPE, null
        );
        element = result.singleNodeValue;
        if (element) {
          FSB.elementCache.set(sanitized, element);
        }
        return element;
      } catch (e) {
        logger.warn('XPath evaluation failed', {
          sessionId: FSB.sessionId, selector: sanitized, error: e.message
        });
        return null;
      }
    }

    // Check if selector contains shadow DOM piercing operator
    if (sanitized.includes('>>>')) {
      const parts = sanitized.split('>>>').map(s => s.trim());
      try {
        element = document.querySelector(parts[0]);
      } catch (e) {
        logger.warn('Invalid selector part', { sessionId: FSB.sessionId, part: parts[0], error: e.message });
        return null;
      }

      for (let i = 1; i < parts.length && element; i++) {
        const shadowRoot = FSB.openOrClosedShadowRoot(element);
        if (shadowRoot) {
          try {
            element = shadowRoot.querySelector(parts[i]);
          } catch (e) {
            logger.warn('Invalid shadow selector part', { sessionId: FSB.sessionId, part: parts[i], error: e.message });
            return null;
          }
        } else {
          element = null;
        }
      }
    } else {
      // Regular querySelector for non-shadow DOM
      try {
        element = document.querySelector(sanitized);
      } catch (e) {
        logger.warn('querySelector failed', { sessionId: FSB.sessionId, selector: sanitized, error: e.message });
        return null;
      }
    }

    // Unicode-aware aria-label fallback: if querySelector returned null and the
    // selector contains aria-label, try matching after stripping invisible chars
    if (!element && sanitized.includes('aria-label')) {
      element = FSB.findElementByNormalizedAriaLabel(sanitized);
      if (element) {
        logger.debug('Found element via Unicode-normalized aria-label fallback', {
          sessionId: FSB.sessionId, selector: sanitized
        });
      }
    }

    // data-fsb-id fallback: if the selector looks like an FSB semantic elementId
    // (contains underscores, no CSS special chars like #.[: at start) look it up
    // by the data-fsb-id attribute stamped during get_dom_snapshot.
    if (!element && /^[a-z][a-z0-9_-]+$/.test(sanitized)) {
      try {
        element = document.querySelector('[data-fsb-id="' + sanitized + '"]');
        if (element) {
          logger.debug('Found element via data-fsb-id fallback', {
            sessionId: FSB.sessionId, selector: sanitized
          });
        }
      } catch (_e) {}
    }

    // SPEED-04: Cache the found element for future lookups
    if (element) {
      FSB.elementCache.set(sanitized, element);
    }

    return element;
  }

  /**
   * Resolve a compact ref (e.g., "e1") to a DOM element.
   * Falls back to CSS selector if the WeakRef has been garbage-collected.
   * @param {string} ref - The compact ref string (e.g., "e1")
   * @returns {Element|null} The resolved DOM element, or null if not found
   */
  function resolveRef(ref) {
    const resolved = FSB.refMap.resolve(ref);
    if (!resolved) return null;
    if (!resolved.stale) {
      // Cache the element under its selector for tool reuse
      if (resolved.selector) FSB.elementCache.set(resolved.selector, resolved.element);
      return resolved.element;
    }
    // WeakRef dead or element disconnected -> fallback to CSS selector
    if (resolved.selector) {
      const fallback = querySelectorWithShadow(resolved.selector);
      if (fallback) {
        logger.debug('Resolved stale ref via CSS fallback', {
          sessionId: FSB.sessionId, ref, selector: resolved.selector
        });
      }
      return fallback;
    }
    return null;
  }

  // Query all elements including shadow DOM
  function querySelectorAllWithShadow(selector) {
    // Sanitize selector first to remove invalid pseudo-selectors
    const sanitized = sanitizeSelector(selector);
    if (!sanitized) {
      logger.warn('Cannot queryAll with invalid selector', { sessionId: FSB.sessionId, selector });
      return [];
    }

    const results = [];

    // Regular query first
    try {
      results.push(...document.querySelectorAll(sanitized));
    } catch (e) {
      logger.warn('querySelectorAll failed', { sessionId: FSB.sessionId, selector: sanitized, error: e.message });
      return [];
    }

    // Then search in all shadow roots
    function searchShadowRoots(root) {
      try {
        const elements = root.querySelectorAll('*');
        for (const element of elements) {
          if (element.shadowRoot) {
            try {
              results.push(...element.shadowRoot.querySelectorAll(sanitized));
            } catch (e) {
              // Ignore errors in shadow roots
            }
            searchShadowRoots(element.shadowRoot);
          }
        }
      } catch (e) {
        // Ignore errors during shadow root traversal
      }
    }

    searchShadowRoots(document);
    return results;
  }

  // ============================================================================
  // MULTI-SELECTOR GENERATION
  // ============================================================================

  // Generate multiple selectors for an element with ARIA-first strategy
  function generateSelectors(element, semanticId = null) {
    const selectors = [];
    const selectorScores = new Map(); // Track stability scores

    // 0. Semantic ID selector (if available) - for AI reference
    if (semanticId && semanticId !== `elem_${element.tagName.toLowerCase()}`) {
      // Add as a comment selector for AI to understand element purpose
      const semanticSelector = `[data-fsb-id="${semanticId}"]`; // Virtual selector for AI understanding
      selectors.push(semanticSelector);
      selectorScores.set(semanticSelector, 11); // Highest priority for AI comprehension
    }

    // 1. ARIA selectors (highest priority - most stable)
    // Aria-label selector -- strip invisible Unicode control chars so AI gets clean selectors
    if (element.getAttribute('aria-label')) {
      const rawLabel = element.getAttribute('aria-label');
      const cleanLabel = FSB.stripUnicodeControl(rawLabel);
      // Emit clean selector as primary (AI can match it reliably)
      const cleanSelector = `[aria-label="${cleanLabel}"]`;
      selectors.push(cleanSelector);
      selectorScores.set(cleanSelector, 10); // Highest score
      // If raw differs from clean, also emit raw as lower-priority fallback
      if (rawLabel !== cleanLabel) {
        const rawSelector = `[aria-label="${rawLabel}"]`;
        selectors.push(rawSelector);
        selectorScores.set(rawSelector, 9);
      }
    }

    // Role + aria attributes combo
    const role = element.getAttribute('role');
    if (role) {
      let roleSelector = `[role="${role}"]`;

      // Add aria-labelledby for more specificity
      if (element.getAttribute('aria-labelledby')) {
        roleSelector += `[aria-labelledby="${element.getAttribute('aria-labelledby')}"]`;
      }
      // Add aria-describedby for additional context
      else if (element.getAttribute('aria-describedby')) {
        roleSelector += `[aria-describedby="${element.getAttribute('aria-describedby')}"]`;
      }

      selectors.push(roleSelector);
      selectorScores.set(roleSelector, 9);
    }

    // Other ARIA attributes
    const ariaAttrs = ['aria-controls', 'aria-owns', 'aria-expanded', 'aria-selected', 'aria-checked'];
    for (const attr of ariaAttrs) {
      if (element.hasAttribute(attr)) {
        const selector = `[${attr}="${element.getAttribute(attr)}"]`;
        selectors.push(selector);
        selectorScores.set(selector, 8);
      }
    }

    // 2. Test ID selector (very stable for testing)
    if (element.getAttribute('data-testid')) {
      const selector = `[data-testid="${element.getAttribute('data-testid')}"]`;
      selectors.push(selector);
      selectorScores.set(selector, 9);
    }

    // 3. ID selector (stable but may not always exist)
    if (element.id && !isAutoGeneratedId(element.id)) { // Skip auto-generated IDs
      const selector = `#${CSS.escape(element.id)}`;
      selectors.push(selector);
      selectorScores.set(selector, 8);
    }

    // 4. Semantic HTML5 selectors
    const semanticTags = ['nav', 'main', 'header', 'footer', 'section', 'article', 'aside'];
    if (semanticTags.includes(element.tagName.toLowerCase())) {
      const tagSelector = element.tagName.toLowerCase();
      // Add context if available
      if (element.className && typeof element.className === 'string') {
        const primaryClass = element.className.trim().split(/\s+/)[0];
        if (primaryClass && !primaryClass.match(/^js-|^css-|^is-|^has-/)) {
          const selector = `${tagSelector}.${CSS.escape(primaryClass)}`;
          selectors.push(selector);
          selectorScores.set(selector, 7);
        }
      } else {
        selectors.push(tagSelector);
        selectorScores.set(tagSelector, 6);
      }
    }

    // 5. Name attribute selector (good for forms)
    if (element.name) {
      const selector = `[name="${CSS.escape(element.name)}"]`;
      selectors.push(selector);
      selectorScores.set(selector, 7);
    }

    // 6. Class selector (less stable, filter out dynamic classes)
    if (element.className && typeof element.className === 'string') {
      const classes = filterDynamicClasses(element.className).slice(0, 2); // Limit to 2 most significant classes

      if (classes.length > 0) {
        const selector = `.${classes.map(c => CSS.escape(c)).join('.')}`;
        selectors.push(selector);
        selectorScores.set(selector, 5);
      }
    }

    // 7. Text content selector for interactive elements
    if (['BUTTON', 'A', 'LABEL'].includes(element.tagName) && element.textContent) {
      const text = element.textContent.trim().substring(0, 30);
      if (text && text.length > 2) {
        // XPath selector for exact text match
        const selector = `//${element.tagName.toLowerCase()}[normalize-space(.)="${text}"]`;
        selectors.push(selector);
        selectorScores.set(selector, 6);
      }
    }

    // 8. Input type specific selectors
    if (element.tagName === 'INPUT' && element.type) {
      const typeSelector = `input[type="${element.type}"]`;
      if (element.placeholder) {
        const selector = `${typeSelector}[placeholder="${CSS.escape(element.placeholder)}"]`;
        selectors.push(selector);
        selectorScores.set(selector, 6);
      } else {
        selectors.push(typeSelector);
        selectorScores.set(typeSelector, 4);
      }
    }

    // 9. Nth-child as last resort (least stable)
    if (selectors.length === 0) {
      const parent = element.parentElement;
      if (parent) {
        const siblings = Array.from(parent.children);
        const index = siblings.indexOf(element) + 1;
        const parentSelector = generateBasicSelector(parent);
        if (parentSelector) {
          const selector = `${parentSelector} > ${element.tagName.toLowerCase()}:nth-child(${index})`;
          selectors.push(selector);
          selectorScores.set(selector, 2);
        }
      }
    }

    // Validate uniqueness for each selector and adjust scores
    const validatedSelectors = selectors.map(selector => {
      const isXPath = selector.startsWith('//');
      const validation = isXPath
        ? validateXPathUniqueness(selector)
        : validateSelectorUniqueness(selector);

      let score = selectorScores.get(selector) || 0;

      // Adjust score based on uniqueness
      if (!validation.isValid) {
        score = 0; // Invalid selector
      } else if (validation.isUnique) {
        score += 5; // Bonus for unique selectors
      } else if (validation.count === 0) {
        score = 0; // No matches
      } else {
        score = Math.max(score - 3, 1); // Penalty for non-unique
      }

      return {
        selector,
        score,
        isUnique: validation.isUnique,
        matchCount: validation.count
      };
    });

    // Sort: unique first, then by score
    const sortedSelectors = validatedSelectors.sort((a, b) => {
      if (a.isUnique !== b.isUnique) {
        return b.isUnique ? 1 : -1; // Unique selectors first
      }
      return b.score - a.score; // Then by score
    });

    // PERFORMANCE: Return only top 3 selectors (was 5) to reduce payload size
    // Most elements only need 2-3 good selectors; the extra ones are rarely used
    return sortedSelectors.slice(0, 3);
  }

  /**
   * PERFORMANCE: Generate minimal selectors on-demand based on action type
   * This is more efficient than always generating 5+ selectors per element
   * @param {Element} element - The DOM element
   * @param {string} actionType - The type of action (click, type, extract, etc.)
   * @returns {Array} Array of selector objects with score
   */
  function generateSelectorsForAction(element, actionType = 'default') {
    const selectors = [];
    const selectorScores = new Map();

    // Best: ID (if not auto-generated)
    if (element.id && !isAutoGeneratedId(element.id)) {
      const selector = `#${CSS.escape(element.id)}`;
      selectors.push(selector);
      selectorScores.set(selector, 10);
    }

    // Good: test-id attributes
    const testId = element.getAttribute('data-testid') || element.getAttribute('data-test-id');
    if (testId) {
      const selector = `[data-testid="${testId}"]`;
      selectors.push(selector);
      selectorScores.set(selector, 9);
    }

    // ARIA label (especially good for click actions)
    if (actionType === 'click' || actionType === 'default') {
      const ariaLabel = element.getAttribute('aria-label');
      if (ariaLabel) {
        const selector = `[aria-label="${ariaLabel}"]`;
        selectors.push(selector);
        selectorScores.set(selector, 9);
      }
    }

    // For type actions, prioritize name and label association
    if (actionType === 'type') {
      if (element.name) {
        const selector = `[name="${CSS.escape(element.name)}"]`;
        selectors.push(selector);
        selectorScores.set(selector, 9);
      }

      // Placeholder for inputs
      if (element.placeholder) {
        const selector = `[placeholder="${CSS.escape(element.placeholder)}"]`;
        selectors.push(selector);
        selectorScores.set(selector, 7);
      }
    }

    // Fallback: role attribute
    const role = element.getAttribute('role');
    if (role && selectors.length < 2) {
      const selector = `[role="${role}"]`;
      selectors.push(selector);
      selectorScores.set(selector, 6);
    }

    // Last resort: class-based selector (only if we have < 2 selectors)
    if (selectors.length < 2 && element.className && typeof element.className === 'string') {
      const classes = filterDynamicClasses(element.className).slice(0, 2);

      if (classes.length > 0) {
        const selector = `.${classes.map(c => CSS.escape(c)).join('.')}`;
        selectors.push(selector);
        selectorScores.set(selector, 5);
      }
    }

    // Validate uniqueness for each selector and adjust scores
    const validatedSelectors = selectors.map(selector => {
      const validation = validateSelectorUniqueness(selector);

      let score = selectorScores.get(selector) || 0;

      // Adjust score based on uniqueness
      if (!validation.isValid) {
        score = 0; // Invalid selector
      } else if (validation.isUnique) {
        score += 5; // Bonus for unique selectors
      } else if (validation.count === 0) {
        score = 0; // No matches
      } else {
        score = Math.max(score - 3, 1); // Penalty for non-unique
      }

      return {
        selector,
        score,
        isUnique: validation.isUnique,
        matchCount: validation.count
      };
    });

    // Sort: unique first, then by score; return max 3 selectors
    return validatedSelectors
      .sort((a, b) => {
        if (a.isUnique !== b.isUnique) {
          return b.isUnique ? 1 : -1; // Unique selectors first
        }
        return b.score - a.score; // Then by score
      })
      .slice(0, 3);
  }

  // ============================================================================
  // CONTEXT-AWARE SELECTOR RE-RESOLUTION
  // ============================================================================

  /**
   * Attempt to make a CSS selector uniquely match one element by adding positional constraints.
   * @param {string} selector - The base CSS selector
   * @param {Element} element - The target element
   * @returns {string|null} A unique selector, or null if not uniquifiable
   */
  function makeUnique(selector, element) {
    const matches = document.querySelectorAll(selector);
    if (matches.length === 1) return selector;
    // Try nth-of-type
    const parent = element.parentElement;
    if (parent) {
      const siblings = parent.querySelectorAll(`:scope > ${element.tagName.toLowerCase()}`);
      const idx = Array.from(siblings).indexOf(element);
      if (idx >= 0) {
        const nthSelector = `${selector}:nth-of-type(${idx + 1})`;
        try {
          if (document.querySelectorAll(nthSelector).length === 1) return nthSelector;
        } catch (e) { /* invalid selector */ }
      }
    }
    return null; // Not uniquifiable with this strategy
  }

  /**
   * Context-aware element re-resolution.
   * Attempts to find an element by its last-known context when the primary selector fails.
   * @param {Object} context - Element context from _fsbResolveContext
   * @param {string} [context.role] - Element role or tag
   * @param {string} [context.accName] - Accessible name (aria-label or text content)
   * @param {string} [context.nearbyText] - Parent text content for proximity matching
   * @param {string} [context.parentTag] - Parent element tag name
   * @param {string} [context.parentClasses] - Parent element class names
   * @param {number} [context.position] - Index among parent's children
   * @returns {{element: Element, confidence: number, method: string}|null}
   */
  function reResolveElement(context) {
    if (!context) return null;

    const candidates = [];

    // Strategy 1: Find by role + accessible name
    if (context.role && context.accName) {
      try {
        const byRole = document.querySelectorAll(`[role="${context.role}"]`);
        for (const el of byRole) {
          const name = el.getAttribute('aria-label') || el.textContent?.trim()?.substring(0, 60) || '';
          if (name.includes(context.accName) || context.accName.includes(name)) {
            candidates.push({ element: el, confidence: 0.9, method: 'role+name' });
          }
        }
      } catch (e) { /* invalid role selector */ }
    }

    // Strategy 2: Find by nearby text content
    if (context.nearbyText && context.nearbyText.length > 5) {
      try {
        const searchText = context.nearbyText.substring(0, 50);
        const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
          acceptNode: (node) => node.textContent.includes(searchText) ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT
        });
        const textNode = walker.nextNode();
        if (textNode) {
          const parent = textNode.parentElement;
          if (parent) {
            const nearby = parent.querySelectorAll('button, a, input, [role="button"], [role="link"], [tabindex]');
            for (const el of nearby) {
              candidates.push({ element: el, confidence: 0.6, method: 'nearby_text' });
            }
          }
        }
      } catch (e) { /* tree walker error */ }
    }

    // Strategy 3: Find by parent structure + position
    if (context.parentTag && context.position !== undefined) {
      try {
        const parentSelector = context.parentTag + (context.parentClasses ? `.${context.parentClasses.split(' ')[0]}` : '');
        const parents = document.querySelectorAll(parentSelector);
        for (const parent of parents) {
          const children = parent.querySelectorAll('button, a, input, [role], [tabindex]');
          if (children[context.position]) {
            candidates.push({ element: children[context.position], confidence: 0.5, method: 'parent+position' });
          }
        }
      } catch (e) { /* invalid parent selector */ }
    }

    // Return best candidate
    candidates.sort((a, b) => b.confidence - a.confidence);
    return candidates.length > 0 ? candidates[0] : null;
  }

  // ============================================================================
  // SHADOW DOM DETECTION
  // ============================================================================

  // Check if element is inside shadow DOM
  function isInShadowDOM(element) {
    let node = element;
    while (node && node !== document) {
      if (node.toString() === '[object ShadowRoot]') {
        return true;
      }
      node = node.parentNode || node.host;
    }
    return false;
  }

  // ============================================================================
  // EXPORT TO FSB NAMESPACE
  // ============================================================================

  FSB.generateSelector = generateSelector;
  FSB.generateSelectors = generateSelectors;
  FSB.generateSelectorsForAction = generateSelectorsForAction;
  FSB.generateBasicSelector = generateBasicSelector;
  FSB.findAlternativeSelectors = findAlternativeSelectors;
  FSB.isClickable = isClickable;
  FSB.sanitizeSelector = sanitizeSelector;
  FSB.querySelectorWithShadow = querySelectorWithShadow;
  FSB.resolveRef = resolveRef;
  FSB.querySelectorAllWithShadow = querySelectorAllWithShadow;
  FSB.validateSelectorUniqueness = validateSelectorUniqueness;
  FSB.validateXPathUniqueness = validateXPathUniqueness;
  FSB.isAutoGeneratedId = isAutoGeneratedId;
  FSB.filterDynamicClasses = filterDynamicClasses;
  FSB.isInShadowDOM = isInShadowDOM;
  FSB.AUTO_GENERATED_ID_PATTERN = AUTO_GENERATED_ID_PATTERN;
  FSB.DYNAMIC_CLASS_PATTERNS = DYNAMIC_CLASS_PATTERNS;
  FSB.reResolveElement = reResolveElement;
  FSB.makeUnique = makeUnique;

  window.FSB._modules['selectors'] = { loaded: true, timestamp: Date.now() };
})();
